### ISSUE TITLE
Unable to resolve module 'crypto' as module does not exist in module map

### ISSUE THREAD

**Issue by NarendraSingh88** [boblauer/url-exists#5]
On installing url-exists, I am getting the following error - 

> Unable to resolve module 'crypto' as module does not exist in module map

Please suggest some fix for that.

**Comment by boblauer** [comment]
This must have something to do with `crypto` being a downstream requirement of `request`, but I've never seen this error nor am I familiar with it.  I do know that the `crypto` module used to be an external module, but was later added to the node standard library. Perhaps you're using an older version of node than `request` supports?

I'm not really sure, but I am sure the issue isn't related to this package specifically, so unfortunately I can't really be of much help.
