### ISSUE TITLE
request package Deprecation

### ISSUE THREAD

**Issue by ambrosiora** [boblauer/url-exists#7]
Hi!

First of all, I wanna thank you, because your package is very useful.
Yes, it's simple, but very useful for us.

You have more than 2k weekly downloads on NPM page, that's very impressive.

But, I want to let you know about the https://www.npmjs.com/package/request package you are using.
They warn us that is deprecated, and I'm afraid about that.

Is you taking some preventive actions about this?

Thanks, have a nice day.

**Comment by boblauer** [comment]
Thank you for the kind words. `request` being deprecated shouldn't affect this package, it won't be removed from the npm registry, it's just not getting new features added.
